###
# GetAll category
GET http://localhost:3000/api/categoryUsers/

###
# Get category by id
GET http://localhost:3000/api/categoryUsers/61a316903b1e8cb8bf78dd2a



### 
# Create Category
POST  http://localhost:3000/api/categoryUsers/
Content-Type: application/json

{
    "name": "ADMIN",
    "displayName": "Quản Trị Viên",
    "description": "Thành viên có chức năng quản trị và chức năng của khách hàng"
}



### 
# Update Category
PUT  http://localhost:3000/api/categoryUsers/60a28dc17ceccf23132019da
Content-Type: application/json

{
    "name": "ADMIN",
    "displayName": "Quản Trị Viên",
    "description": "Thành viên có chức năng quản trị website và chức năng của khách hàng"
}


###
# Delete Category
DELETE  http://localhost:3000/api/categoryUsers/60a28cdf7ceccf23132019d7 