###
# GetAll user
GET http://localhost:3000/api/users/
Content-Type: application/json
Authorization: Bearer 1kbsdkhabskbdkjab


###
# Get user by id
GET http://localhost:3000/api/users/60a3f2d8fd84603e8364b8a6


###
# Check Auth user
GET http://localhost:3000/api/users/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEzZjJkOGZkODQ2MDNlODM2NGI4YTYiLCJpYXQiOjE2MjE2MTA2NTl9.Hc8zdUaW5pk286zlUrKMdXzXl_uUT4FL9DjYYE28_RY



### 
# Create user
POST  http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "Nguyễn Thị Diệu Nhi",
    "username":"dieunhi",
    "password":"123",
    "email":"18521694@gm.uit.edu.vn",
    "image": "abc",
    "address":"Đồng Tháp",
    "categoryUser":"61a353993b1e8cb8bf78dd38"
}



### 
# Login
POST  http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username":"son",
    "password":"son"
}



### 
# Update user
PUT  http://localhost:3000/api/users/
Content-Type: application/json

{
    "name": "ADMIN",
    "displayName": "Quản Trị Viên",
    "description": "Thành viên có chức năng quản trị website và chức năng của khách hàng"
}



### 
# Update account user
PUT  http://localhost:3000/api/users/account
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MGEzZjJkOGZkODQ2MDNlODM2NGI4YTYiLCJpYXQiOjE2MjE3NjM0NjJ9.sio40vF1SFDxUF7vSCClTtDDZYHM-iJscQUbEBY6W84

{
    "username": "son",
    "password": "123",
    "newPassword": "123"
}



### 
# Update permission user
PUT  http://localhost:3000/api/users/permission/60a28dc17ceccf23132019da 
Content-Type: application/json
Authorization: Bearer 1kbsdkhabskbdkjabaskjn29hdansdubosdbnj




###
# Delete user
DELETE  http://localhost:3000/api/users/60a28cdf7ceccf23132019d7 