export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS'
export const CREATE = 'CREATE'
export const DELETE_BY_ID = 'DELETE_BY_ID'
export const GET_ORDER_DETAILS_BY_USER_ID = 'GET_ORDER_DETAILS_BY_USER_ID'
