const urlStr = "http://localhost:3000/api";

const LOCAL_STORAGE_TOKEN_NAME = "LOCAL_STORAGE_TOKEN_NAME";
const LOCAL_STORAGE_CART = "LOCAL_STORAGE_CART";
const LOCAL_STORAGE_SEEN_PRODUCT = "LOCAL_STORAGE_SEEN_PRODUCT";
export { urlStr, LOCAL_STORAGE_TOKEN_NAME, LOCAL_STORAGE_CART, LOCAL_STORAGE_SEEN_PRODUCT};